/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ReporteInventario;

import Clases.Empleado;
import Controler.Conexion;
import Controler.ListarDatos;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class Proceso_Empleados extends javax.swing.JFrame {

    /**
     * Creates new form informe
     */
    DefaultTableModel mitabla1=new DefaultTableModel();
     ListarDatos listar = new ListarDatos();
    public Proceso_Empleados() {
        initComponents();
        verEmpleado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REPORTE EMPLEADOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proceso_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proceso_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proceso_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proceso_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proceso_Empleados().setVisible(true);
            }
        });
    }
    public void limpiarTabla1(){
       try {
       DefaultTableModel modelo=(DefaultTableModel) tabla1.getModel();
       int filas=tabla1.getRowCount();
       for (int i = 0;i<=filas; i++) {
          modelo.removeRow(0);
        }
      } catch (Exception e) {}
    }
    public void verEmpleado(){
    Conexion c=new Conexion();
        ArrayList<Empleado>lista1=new ArrayList<>();
        lista1=listar.Listar("SELECT empleado.idempleado,empleado.apellidos,empleado.nombre,empleado.fechacontratacion,"
                + "empleado.direccion,empleado.telefono,empleado.ciudad,cargo.descripcioncargo,horario.horarioinicio "
                + "|| ' - ' || horario.horariofinal AS HORARIOS FROM empleado INNER JOIN cargo ON empleado.idcargo=cargo.idcargo "
                + "INNER JOIN horario ON empleado.idhorario=horario.idhorario");
        
    if (tabla1.getRowCount()==0) {
        tabla1.setModel(mitabla1);
        String[] titulos={"ID","Apellidos","Nombre","Contrato","Direccion","Telefono","Ciudad","Cargo","Horario"};
        mitabla1.setColumnCount(titulos.length);
        mitabla1.setColumnIdentifiers(titulos);
        String[] datos=new String[titulos.length];
       
        for (Empleado l:lista1 ) {
            datos[0]=l.getIdEmpleado();
            datos[1]=l.getApellidos();
            datos[2]=l.getNombre();
            datos[3]=l.getFechaContratacion();
            datos[4]=l.getDireccion();
            datos[5]=l.getTelefono();
            datos[6]=l.getCiudad();
            datos[7]=l.getIdCargo();
            datos[8]=l.getIdHorario();
            mitabla1.addRow(datos);
        }     
    }else{
        limpiarTabla1();
        tabla1.setModel(mitabla1);
        String[] titulos={"ID","Apellidos","Nombre","Contrato","Direccion","Telefono","Ciudad","Id_cargo","Id_horario"};
        mitabla1.setColumnCount(titulos.length);
        mitabla1.setColumnIdentifiers(titulos);
        String[] datos=new String[titulos.length];
       
        for (Empleado l:lista1 ) {
            datos[0]=l.getIdEmpleado();
            datos[1]=l.getApellidos();
            datos[2]=l.getNombre();
            datos[3]=l.getFechaContratacion();
            datos[4]=l.getDireccion();
            datos[5]=l.getTelefono();
            datos[6]=l.getCiudad();
            datos[7]=l.getIdCargo();
            datos[8]=l.getIdHorario();
            mitabla1.addRow(datos);
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
}
